const TRADING_MISTAKES = [
  { emoji: "💸", title: "Stop-loss qo'ymaslik", text: "Warren Buffett: \"Birinchi qoida — pulni yo'qotma. Ikkinchi qoida — birinchi qoidani unutma.\" Har doim stop-loss qo'y!" },
  { emoji: "🎰", title: "Overtrading — haddan ortiq savdo", text: "Kuniga 10-20 ta pozitsiya ochish — bu savdo emas, qimorbozlik. Sabr — eng kuchli strategiya." },
  { emoji: "😤", title: "Qasos savdosi", text: "Minus bo'lgandan so'ng darhol ikki baravar katta pozitsiya ochish — eng xavfli holat. Yo'qotganda emas, aniq signal bo'lganda savdo qil." },
  { emoji: "📈", title: "FOMO", text: "Narx 50% ko'tarilib ketganda yugurish — kech qolganlik belgisi. Bozor har doim imkoniyat beradi, sabr bilan kut." },
  { emoji: "🏦", title: "100% kapitalini bir savdoga qo'yish", text: "Professional treyderlar har savdoga kapitalning 1-5%ini xavf qiladi. Diversifikatsiya — himoya qalqoni." },
  { emoji: "💊", title: "Zarar beruvchi pozitsiyani ushlab turish", text: "\"Narx qaytib keladi\" deb -30%, -50%, -80% ga tushirish — eng katta xato. Kichik yo'qotishni qabul qil." },
  { emoji: "⚡", title: "Kuchli leveraj", text: "50x, 100x leveraj bilan savdo — bu lotereya. Yangi boshlovchilar uchun maksimum 5-10x." },
  { emoji: "🌙", title: "Tunda uyqusiz savdo", text: "Charchagan miyada qabul qilingan qarorlar 80% noto'g'ri. Dam olgan aql — keskin aql." },
  { emoji: "🎯", title: "Take-profit qo'ymaslik", text: "+200% bo'lgan pozitsiyani ochiq qoldirib, natijada -10% bilan chiqish. Foyda — faqat pozitsiyani yopgandan so'ng foyda." },
  { emoji: "🔄", title: "Xatoni takrorlash", text: "George Soros: \"Muhim narsa to'g'ri yoki noto'g'ri emasligingda emas — to'g'ri bo'lganda qancha ishlashingda.\"" },
  { emoji: "📊", title: "Texnik tahlilni o'rganmaslik", text: "Grafiklardagi asosiy naqshlarni bilmasdan savdo qilish — ko'r holda haydashga o'xshaydi." },
  { emoji: "🏃", title: "Tezkor boy bo'lishga urinish", text: "\"Bir oyda 10x qilaman\" — bu fikr bilan boshlanadi ko'p yo'qotishlar. Treyding — marathon, sprint emas." },
  { emoji: "💰", title: "Kredit bilan savdo", text: "Qarz pul bilan savdo — bu psixologik bosim va noto'g'ri qarorlar. Faqat yo'qotishga rozi bo'lgan pulni savdoga qo'y." },
  { emoji: "🗓️", title: "Kundalik yuritmaslik", text: "Har bir savdoni yozib bormaslik — taraqqiyotning eng katta to'sig'i. Yozilmagan savdo — o'rganilmagan dars." },
  { emoji: "😰", title: "Panic selling", text: "Narx 10% tushganda qo'rqib chiqib ketish va keyin o'sha narxdan oshib ketishini kuzatish. Savdoga kirishdan oldin exit strategiyangni aniq bel." },
  { emoji: "🌊", title: "Trendga qarshi savdo", text: "\"Narx juda ko'tarildi, hozir tushadi\" deb short ochish va yonib ketish. Trend — do'sting, u bilan yur." },
  { emoji: "🔍", title: "Due diligence qilmaslik", text: "Telegram da ko'rgan tokenni o'rganmasdan olish. Har doim so'ra: Bu loyiha nima qiladi? Kim qildi?" },
  { emoji: "📣", title: "Influencerlarga ishonish", text: "Twitter/YouTube da mashhur treyderlar seni boy qilmaydi. Hech kim sizning pulingizni o'z pulidan ko'ra ko'proq qadrlamaydi." },
  { emoji: "🔐", title: "Security ni e'tiborsiz qoldirish", text: "Ko'plab treyderlar hack, phishing, scam orqali pul yo'qotadi. Hardware wallet, 2FA — bular ham strategiya." },
  { emoji: "📐", title: "Risk/Reward ni hisoblamaslik", text: "1:1 risk/reward bilan savdo — uzoq muddatda zarar. Har savdoda minimum 1:2 yoki 1:3 risk/reward izla." },
  { emoji: "🌍", title: "Makroiqtisodiyotni e'tiborsiz qoldirish", text: "Fed rate hike, dollar kuchayishi — bular kripto bozorini sezilarli darajada ta'sir qiladi. Global iqtisodiyotdan xabardor bo'l." },
  { emoji: "🏋️", title: "Sog'liqni e'tiborsiz qoldirish", text: "Charchagan, uxlamagan, stress ichidagi treyder — bu yuruvchi bankrot. Sport, uyqu, meditatsiya — bular trading strategiyasi." },
  { emoji: "🎓", title: "O'rganishni to'xtatish", text: "\"Men etarlicha bilaman\" — eng xavfli fikr. Bozor har doim o'zgaradi. Eng yaxshi treyderlar — umrbod talabalar." },
  { emoji: "⚖️", title: "Overconfidence", text: "Bir necha muvaffaqiyatli savdodan so'ng o'zini expert deb hisoblash. Bozor doimo eng aqlli treyderlarni ham sindiradi." },
  { emoji: "🛑", title: "Stop-loss ni ko'chirish", text: "Stop-loss yaqinlashganda uni pastroqqa ko'chirish — o'zini aldash. Stop-loss — qaror, his emas." },
  { emoji: "🌡️", title: "Bozor temperaturasini o'lchamslik", text: "Fear & Greed Index, funding rate — bular bozor kayfiyatini ko'rsatadi. Hammalar qo'rqayotganda sotib ol, hammalar ochko'z bo'lganda sot." },
  { emoji: "📉", title: "Bear bozorida faqat buy", text: "Bozor pasayishida ham ko'tarilishini kutish — pul yo'qotish formulasi. Shorting va hedging strategiyalarini o'rgan." },
  { emoji: "🎲", title: "50/50 fikri", text: "\"50/50 ehtimol\" deb savdo qilish. Professional treyderlar faqat 60-70%+ ehtimollik bo'lgan setaplarda kiradi." },
  { emoji: "📦", title: "Position sizing bilmaslik", text: "Kichik kapital bilan katta savdo — bu roulette. Fixed % risk management o'rgan." },
  { emoji: "🔭", title: "Uzoq muddatli fikr yuritmaslik", text: "Paul Tudor Jones: \"Hech narsaga shunchalik mahliyo bo'lmangki, katta manzaradan ko'zingiz uzilsa.\"" },
  { emoji: "📱", title: "Narxni har 5 daqiqada tekshirish", text: "Obsessiv narx tekshirish — stress va noto'g'ri qarorlar. Alert qo'y va olib ket." },
  { emoji: "🎭", title: "Savdoni o'yin deb bilish", text: "Trading — real pul bilan ehtimoliyat o'yini. Har qarorning moliyaviy oqibatini his qil." },
  { emoji: "🧠", title: "Confirmation bias", text: "Faqat o'z fikringni tasdiqlaydigan ma'lumotlarni qidirish. Har doim o'zingga qarshi argumentlarni ham o'rna." },
  { emoji: "🏠", title: "Hayotiy pul bilan savdo", text: "Ijara puli, oziq-ovqat pulini trading ga qo'yish — psixologik bosim va noto'g'ri qarorlar. Faqat ortiqcha pul bilan savdo qil." },
  { emoji: "💎", title: "Diamond hands — noto'g'ri vaqtda", text: "\"HODL!\" ba'zan yo'qotishlarni qoplash uchun aytiladi. Stop-loss — diamond hands dan qimmatroq." },
  { emoji: "🔁", title: "Foyda ni darhol qayta investitsiya", text: "Har foydani yangi savdoga solish — ochko'zlik. Foyda bir qismini olib qo'y." },
  { emoji: "📍", title: "Anchoring bias", text: "\"Bitcoin bir vaqt 69K bo'lgan, yana o'sha yerga boradi\" — noto'g'ri kutish. Narx o'tmishga qarzdor emas." },
  { emoji: "🤖", title: "Indikatorlarga ko'r-ko'rona ishonish", text: "RSI, MACD — bular vosita, haqiqat emas. Indikatorlar yordamchi, asosiy emas." },
  { emoji: "🌐", title: "Faqat yangiliklarga ishonish", text: "\"Elon Musk tweet qildi, DOGE olaman!\" Ko'pincha yangilikni ko'rishguncha narx allaqachon harakat qilib bo'lgan." },
  { emoji: "🎪", title: "Pump and dump", text: "\"X coin 1000% o'sadi!\" — ko'pincha pump sxemasi. Kichik market cap tokenlar bilan ehtiyot bo'l." },
  { emoji: "🧮", title: "Komissiyalarni hisoblasmaslik", text: "Har savdodagi 0.1% komissiya — ular sezilarli darajada foyda ni kamaytiradi. Haqiqiy foyda = Gross foyda - Komissiya." },
  { emoji: "⏰", title: "Timeframe ni aralashtirib yuborish", text: "Daily chartda signal ko'rib, 1 minutlik chartda savdo qilish. Bir timeframe tanlang va unga sodiq bo'ling." },
  { emoji: "🏆", title: "Win streak dan mast bo'lish", text: "5 marta ketma-ket yutgandan so'ng invincible his qilish — eng xavfli payt." },
  { emoji: "👥", title: "Telegram guruhlariga ishonish", text: "\"VIP signallar\" guruhlarining 90%i firibgarlik. Boshqaning signali bilan boy bo'lmaysan." },
  { emoji: "🔮", title: "Bozorni bashorat qilish", text: "\"Bitcoin 100K ga boradi\" — bunday bashoratlar noto'g'ri. Tendentsiyaga ergash, bashorat qilma." },
  { emoji: "🕯️", title: "Candlestick pattern larni bilmaslik", text: "Doji, Hammer, Engulfing — bular narx harakatining tili. Bu patternlarni o'rganish — narx nima deyotganini eshitish." },
  { emoji: "🌱", title: "Natijani emas, jarayonni baholash", text: "Yaxshi qaror ham ba'zan yomon natija berishi mumkin. Strategiyangni natija emas, mantiqqa ko'ra baholang." },
  { emoji: "🔥", title: "Barcha tuxumni bir savatchaga qo'yish", text: "Bir tokenga hamma kapital — bu diversifikatsiya emas. Risk ni bo'lib tashlang." },
  { emoji: "🎯", title: "Maqsadsiz savdo", text: "\"Nima bo'lsa bo'lar\" deb savdo qilish — bu umid, strategiya emas. Har savdoda aniq rejang bo'lsin." },
  { emoji: "📊", title: "Statistikasiz ishlash", text: "Win rate, risk/reward, expectancy — bularni bilmasdan savdo qilish ko'r uchish. O'z raqamlaringni bil." },
];

function getDailyQuote() {
  const dayOfYear = Math.floor((Date.now() - new Date(new Date().getFullYear(), 0, 0)) / 86400000);
  return TRADING_MISTAKES[dayOfYear % TRADING_MISTAKES.length];
}

module.exports = { TRADING_MISTAKES, getDailyQuote };
